### ISSUE TITLE
NoSuchMethodError when trying to query Bigtable from dataflow

### ISSUE THREAD

**Issue by darshanmehta10** [GoogleCloudPlatform/cloud-bigtable-client#1857] opened 2018-06-21 10:24 UTC
Dependencies:

```
<dependency>
    <groupId>com.google.cloud.bigtable</groupId>
    <artifactId>bigtable-hbase-beam</artifactId>
    <version>1.3.0</version>
</dependency>

<dependency>
  <groupId>com.google.cloud.bigtable</groupId>
  <artifactId>bigtable-hbase-1.x</artifactId>
  <version>1.3.0</version>
</dependency>
```

Code to query :

`ResultScanner resultScanner = table.getScanner(scan);` 

Exception : 

```
java.lang.NoSuchMethodError: com.google.bigtable.v2.ReadRowsRequest.getAppProfileId()Ljava/lang/String;
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.readFlatRows(BigtableDataGrpcClient.java:450)
	at com.google.cloud.bigtable.hbase.AbstractBigtableTable.getScanner(AbstractBigtableTable.java:293)
...
```

Maybe I need to add/update the dependencies?

**Comment by sduskis** [comment] 2018-06-21 11:35
We do some package renaming, which causes this problem.  Please remove `bigtable-hbase-1.x`, and things will work.

**Comment by sduskis** [comment] 2018-06-21 12:59
We can't really solve the underlying problem, so I'm going to have to close this issue.

**Comment by darshanmehta10** [comment] 2018-06-21 16:57
@sduskis have made those changes, however, now I can't get `FilterAdapter` to get the correct `RowFilter`, e.g.:

```
FilterList typeFilterList = new FilterList(Operator.MUST_PASS_ONE);
typeFilterList.addFilter(filter1);
typeFilterList.addFilter(filter2);
typeFilterList.addFilter(filter3);

FilterListAdapter filterListAdapter = new FilterListAdapter(FilterAdapter.buildAdapter());

BigTableIO.read()
    .withRowFilter(filterListAdapter.adapt(null, filterList));
```
Last line in the above snippet fails with the following compilation error:

> The method withRowFilter(com.google.bigtable.v2.RowFilter) in the type BigtableIO.Read is not applicable for the arguments (com.google.bigtable.repackaged.com.google.bigtable.v2.RowFilter)

This is happening because of the same reason I guess? The purpose here is to use `BigTableIO` with `filter`. Is there any other way to make it work?

**Comment by sduskis** [comment] 2018-06-21 17:20
Yup.  If you're using `bigtable-hbase-beam`, you won't be able to use any artifacts from it in BigtableIO directly.

The core of the problem is about major issues with dependency management relating to Beam and cloud-bigtable-client.  There are a few ways to fix the problem:

1. Use CloudBigtableIO instead of BigtableIO for all Bigtable related activity.
2. Use `bigtable-hbase-1.x` as a dependency, but make sure that you use it after all Beam dependencies.  Also, you're going to have to exclude a bunch of dependencies from `bigtable-hbase-1.x`, and I'm not sure what the comprehensive

**Comment by sduskis** [comment] 2018-06-27 17:36
Another option is to create `RowFilter`s directly instead of using the adapter.

I'm going to close this for now, since I don't think that there's anything actionable.

**Closed by sduskis** 2018-06-27 17:36 UTC
