### ISSUE TITLE
dataflow connector in version 0.3.0 seems broken

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/cloud-bigtable-client#829] opened 2016-05-10 06:52 UTC
When using version 0.3.0 of the hbase dataflow client, I see a lot of messages in cloud logging:

```
{
  metadata: {…}    
  insertId: "2016-05-09|23:49:01.018422-07|10.106.46.68|-15814046"    
  log: "dataflow.googleapis.com/worker"    
  structPayload: {
    message: "No operations completed within the last 0 seconds. There are still 1 rpcs and 1 retries in progress."      
    work: "�����*account.city.protocol 39364842630012JWillingboro-109549253860703936"      
    thread: "65"      
    worker: "transform-staging2-05092343-19a5-harness-r8k8"      
    logger: "com.google.bigtable.repackaged.com.google.cloud.grpc.async.RpcThrottler"      
    stage: "F23"      
    job: "2016-05-09_23_43_33-1529243700710151066"      
  }
}
```

These seem to be bad and when I look at the write requests in the bigtable metrics page, I don't see any write requests being made. I believe something might be very wrong or not configured properly. Is there a way to diagnose this further?

**Comment by sduskis** [comment] 2016-05-10 18:17
Another user has reported a similar issue around the same time.  There was a rolling server restart, which  usually isn't a problem.  We hear about these issues infrequently, but often enough.  We're going to do some testing to see if we can reliably reproduce the issue.

When this issue happens we have no indication that there's a problem.  We'll work with gRPC to get ideas on how to recover from these failure conditions.

**Comment by ankurcha** [comment] 2016-05-26 22:02
any updates on this?

**Comment by sduskis** [comment] 2016-05-26 22:43
Nothing yet.  We tried new versions of gRPC (0.14.0) for 0.3.1-SNAPSHOT, but we had to revert that change (back to grpc 0.13.1) due to other problems.  We've done quite a bit of work to try to reproduce this problem, and got hanging a couple of times out of many tries.  We are using a modified version of our go in memory bigtable fake server to have more control over server side throughput (i.e. add in random slowness and timeouts).

We've spent quite a while on simply reproducing the issue, and haven't found a root cause.

**Comment by ankurcha** [comment] 2016-05-27 08:01
Thanks for the reply. I tried this today and, at least on my dataflow job, I'm able to consistently reproduce the behaviour mentioned above. If there is a way I can provide you a trace or other details that may be helpful, please let me know.

**Comment by sduskis** [comment] 2016-07-20 17:56
There were some specific usage patterns in your project that we discussed offline that seemed to be the problem.  I'm closing this issue, because there doesn't seem to be any active work we ought to do to fix this.

**Comment by amankhurpal** [comment] 2016-09-16 14:23
Could you guys please share the usage patterns which causes this problem, I want to check the same in my project as I am also facing the same problem.

Thanks,
Aman

**Comment by sduskis** [comment] 2016-09-16 16:00
We're working on documentation for this.  The short answer, is that this happens when the load against Cloud Bigtable is higher than it can handle.  That causes latency and problems with handling the RPCs that trigger strange issues in the gRPC library.  A couple things to keep in mind

- As gRPC releases new versions, they fix various corner cases.  Cloud Bigtable client uses the new gRPC releases as soon as we can.  The 0.9.2 version, for example, uses the 1.0.0 gRPC library.  The Cloud Bigtable 0.3.0 - 0.9.1 used a much older 0.14.1 version.  There still are corner cases that are being worked on

- Cloud Bigtable node counts are important.  Cloud Bigtable can get overloaded.  The symptoms of overloading show up on the CPU Usage graph on the cloud console in the Bigtable section.  You want to be at no more than 80% CPU Usage for the duration of the Dataflow job.  If your job uses too much CPU, you need to increase Cloud Bigtable nodes (which can be done during the job, and can be done programmatically) and you also need to set a reasonable maximum number of dataflow workers.  The rule of thumb is 3 worker CPUs per 1 Cloud Bigtable node. So a 30 node Bigtable cluster will support at most 22 n1-standard-4 workers.

We're working on documenting this publicly.

**Comment by amankhurpal** [comment] 2016-09-16 16:16
Thanks! Solomon

the pattern which I am observing in my dataflow job is that this warning occurs towards the end of the job and there is no CPU load on bigtable

**Comment by sduskis** [comment] 2016-09-16 16:30
Yup.  That is indeed what happens.  There is a failure in the middle of the job, and somehow we lose the acknowledgement that the operation succeeded.

**Comment by sduskis** [comment] 2016-09-16 16:32
I'll create a new issue to track this that focuses on the hanging behavior and is less specific to the client version.

**Closed by sduskis** 2016-09-16 16:32 UTC

**Comment by sduskis** [comment] 2016-09-16 17:47
I opened #1013 to explain the issue and to track possible solutions.
