### ISSUE TITLE
Issue with 0.9.7 and protobuf version

### ISSUE THREAD

**Issue by jakon89** [GoogleCloudPlatform/cloud-bigtable-client#1436] opened 2017-06-28 08:16 UTC
Hi!

I see that in `bigtable-hbase-1.2 0.9.7` protobuf version changed to 3.2 however newest versions `1.2.6` of `hbase-client` and `hbase-common` still use protobuf in version 2.5.0. 

I created simple project that reproduces issue I faced:
https://github.com/jakon89/google-bt-hbase

It gives following stacktrace:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/LiteralByteString
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.hadoop.hbase.util.ByteStringer.<clinit>(ByteStringer.java:44)
	at org.apache.hadoop.hbase.filter.SingleColumnValueFilter.convert(SingleColumnValueFilter.java:311)
	at org.apache.hadoop.hbase.filter.SingleColumnValueFilter.toByteArray(SingleColumnValueFilter.java:329)
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.toFilter(ProtobufUtil.java:1492)
	at org.apache.hadoop.hbase.filter.FilterList.toByteArray(FilterList.java:367)
	at Main.main(Main.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.LiteralByteString
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more`

Is this break intentional or not?

**Comment by sduskis** [comment] 2017-06-29 17:47
We just released bigtable-hbase-1.x:1.0.0-pre1 that fixes a lot of the dependency related issues (the literal "x" should replace "2".  [Here are some notes about the change](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/1048#issuecomment-310543386).

**Comment by sduskis** [comment] 2017-06-30 14:01
Thanks for putting the example together.  I tried with bigtable-hbase-1.2:1.0.0-pre1, and it had other failure.  bigtable-hbase-1.x:1.0.0-pre1 works fine, and is our recommended option.  We'll fix the problem for bigtable-hbase-1.2:1.0.0-pre2

**Comment by jakon89** [comment] 2017-06-30 14:14
Thanks, appreciate quick help.

I just ran tests cases with `bigtable-hbase-1.2:1.0.0` and they passed however I am worried about 'pre' suffix. I assume that these versions suffix shouldn't go to any env except local/qa. Is there any GA date set for `bigtable-hbase-1.2:1.0.0` version(or other version that fixes the issue)?

**Comment by igorbernstein2** [comment] 2017-06-30 14:23
hbase-1.2 has always had the issue with mismatched protobuf version:
https://mvnrepository.com/artifact/com.google.cloud.bigtable/bigtable-hbase-1.2/0.9.7

I specifically kept that mismatch to keep backwards compatibility during the transition to the new 1.x 
artifacts.

Which is why we reworked the dependencies in the new 1.x artifacts. We consider 1.0.0-pre1 to be stable and recommend general usage of it. We recommend most of our users to use bigtable-hbase-1.x. However if you need hadoop compatible dependencies please use bigtable-hbase-1.x-hadoop. 

Here is a short description of the new artifacts:

bigtable-hbase-1.x: depends on hbase-shaded-client and exposes grpc and modern version of protobuf. This artifact is meant for standalone usage in webapps, beam, and other environments where the user is in control of their dependencies. This contains the actual connection implementation for hbase 1. It doesn't require any shading and allows for source navigation in ides. This should be the default choice for most users.

bigtable-hbase-1.x-shaded: this artifact doesn't contain any java source files, but uses the maven shade plugin to relocate all internal dependencies. This is meant for environments where the user is not in control of their dependencies and is mostly an implementation detail for dataflow 1.x that will eventually be deprecated in favor of beam. Source navigation will be partially broken for this artifact: you will be able to navigate to the hbase connector code, but navigation to the underlying core client will be broken. However this is just a stopgap measure until we transition to beam.

bigtable-hbase-1.x-hadoop: this is similar the -shaded variant but exposes Hadoop compatible dependencies. This is meant to be used in mapreduce jobs where the mapreduce framework injects jars into the user'a classpath. This will have similar limitations as the -shaded variant: you will be able to navigate to hbase compatibility code, but not the underlying core client. Unfortunately I don't think this is something we can do anything about. I would appreciate any suggestions.

**Comment by igorbernstein2** [comment] 2017-06-30 14:24
I'm going close this issue as intended behavior.

**Closed** 2017-06-30 14:33 UTC

**Comment by sduskis** [comment] 2017-06-30 17:06
https://github.com/jakon89/google-bt-hbase does this:

> `new FilterList(Operator.MUST_PASS_ALL, rowFilters).toByteArray();`

The `.toByteArray()` doesn't work correctly, and has not for a while.  The `-1.x` version supports it.
