### ISSUE TITLE
Support for MultiRowRangeFilter

### ISSUE THREAD

**Issue by Naveg** [GoogleCloudPlatform/cloud-bigtable-client#1008] opened 2016-09-12 18:10 UTC
Taking a cursory glance at the `ScanAdapter`, it looks like the underlying `RowSet` supports multiple `RowRange`s. Would this make it possible to support HBase's [`MultiRowRangeFilter`](https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/filter/MultiRowRangeFilter.html)?

**Comment by sduskis** [comment] 2016-09-12 18:14
We should be able to support this.  This sounds like a great addition.  It will be the first time we have a feature that exists for the 1.1 and 1.2 implementations, but not 1.0; this Filter was introduced in 1.1+.  I'll think through how to make this work effectively.

**Comment by vc13819** [comment] 2016-12-15 03:13
+1. We also have a need for this.

**Comment by sduskis** [comment] 2016-12-15 04:54
The most difficult part of this request is that this filter exists in HBase 1.1+.  Maybe the easiest thing to do is to get rid of HBase 1.0 support.

One alternative is to use Table.get(List<Get>) which pretty much does the same work under the covers.

**Comment by vc13819** [comment] 2017-01-26 14:09
Pretty please nudge to prioritize this request:)
Our requirement is to do scan across multiple blocks of contiguous rows (I only know the start and end rows, not the rowids in the middle). Currently I am doing by doing multiple scans in parallel. That obviously ends up needing a lot of threads. I am hoping that if we do get MultiRowRangeFilter this would be better than the current setup for us.

**Comment by sduskis** [comment] 2017-01-27 03:20
There are a few of options to make `RangeSet`s work:

1) Add a method in BigtableTable that takes a `RangeSet` and a `Scan`, or just a `RowFilter`.  You'd have to cast to a BigtableTable.  This is simple to implement, and would allow for more complicated scenarios that take advantage of other aspects of `RowFilter`. 

2) Add a `BigtableMultiRowRangeFilter` that would have slightly different meaning that a `MultiRowRangeFilter`.  We'd  allow only one `BigtableMultiRowRangeFilter` and ignore any MUST_PASS_ONE semantics.  We'd also throw exceptions if multiple `BigtableMultiRowRangeFilter` are set, or if `setStart` or `setStop` were set in addition to a `BigtableMultiRowRangeFilter`.

3) Add support for `MultiRowRangeFilter`.  Throw exceptions under the same conditions as `BigtableMultiRowRangeFilter`.  Also, throw exceptions if there is a `ListFilter` with MUST_PASS_ONE as part of the scan.

Do you have a preference?

**Comment by vc13819** [comment] 2017-01-27 04:11
On Fri, Jan 27, 2017 at 8:50 AM, Solomon Duskis <notifications@github.com>
wrote:

> There are a few of options to make RangeSets work:
>
>    1.
>
>    Add a method in BigtableTable that takes a RangeSet and a Scan, or
>    just a RowFilter. You'd have to cast to a BigtableTable. This is
>    simple to implement, and would allow for more complicated scenarios that
>    take advantage of other aspects of RowFilter.
>    2.
>
>    Add a BigtableMultiRowRangeFilter that would have slightly different
>    meaning that a MultiRowRangeFilter. We'd allow only one
>    BigtableMultiRowRangeFilter and ignore any MUST_PASS_ONE semantics.
>    We'd also throw exceptions if multiple BigtableMultiRowRangeFilter are
>    set, or if setStart or setStop were set in addition to a
>    BigtableMultiRowRangeFilter.
>    3.
>
>    Add support for MultiRowRangeFilter. Throw exceptions under the same
>    conditions as BigtableMultiRowRangeFilter. Also, throw exceptions if
>    there is a ListFilter with MUST_PASS_ONE as part of the scan.
>
> Do you have a preference?
>
IMO 3 is the best. (It keeps the most conformity to hbase API, which can
only be a good thing:).
Between 2 and 1, I have a slight preference for 2

**Comment by Naveg** [comment] 2017-01-27 06:03
I tend to agree. We try to keep our code HBase compatible as much as possible. We do have a couple cases of `if (connection instanceof BigtableConnection) / else` though, so it isn't a deal breaker.

**Comment by vc13819** [comment] 2017-02-10 02:01
Wow. Thanks.
Is there an early access release we can give this a spin. Can't wait!!

**Comment by sduskis** [comment] 2017-02-10 02:47
We release SNAPSHOT versions.  0.9.6-SNAPSHOT has this feature.  See [here](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/hello-world/pom.xml#L42) for how to add the snapshot repository to your pom.xml.

**Comment by vc13819** [comment] 2017-02-10 03:16
To confirm.
To use this we need to create a BigtableExtendedScan instead of Scan and
populate it directly. The usage is not via MultiRowRangeFilter.
Is that right?

**Comment by vc13819** [comment] 2017-02-10 11:56
Moved the code to start using BigtableExtendedScan.
Initial results look very promising. The performance for multiple lookups
with extended scan is much better than doing the same in parallel.

**Comment by vc13819** [comment] 2017-02-10 15:39
Seeing some thread related errors:


17:51:04.657com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl
<init>:
[com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl-1]
Created with target bigtableadmin.googleapis.com:443
17:51:05.749com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl
<init>:
[com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl-6]
Created with target bigtable.googleapis.com:443
17:51:05.761com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl
<init>:
[com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl-7]
Created with target bigtable.googleapis.com:443
17:51:05.778com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl
<init>:
[com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl-8]
Created with target bigtable.googleapis.com:443
17:51:06.902com.google.apphosting.vmruntime.VmRequestThreadFactory
interruptRequestThreads: Request thread grpc-timer-0 is still alive,
forcing interrupt.
17:51:06.906com.google.apphosting.vmruntime.VmRequestThreadFactory
interruptRequestThreads: Request thread grpc-default-executor-0 is still
alive, forcing interrupt.
17:51:06.909com.google.apphosting.vmruntime.VmRequestThreadFactory
interruptRequestThreads: Request thread grpc-shared-destroyer-0 is still
alive, forcing interrupt.


Once a thread is interrupted, the VmRequestThreadFactory gets into a state
that does not allow any more thread creation.
Which eventually leads to this error:

Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException:
UNKNOWN: Name resolution failed at
com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(
Status.java:530
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2FStatus.java&line=530&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at com.google.cloud.bigtable.grpc.async.AbstractRetryingRpcListener.onClose(
AbstractRetryingRpcListener.java:147
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fasync%2FAbstractRetryingRpcListener.java&line=147&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at com.google.cloud.bigtable.grpc.scanner.ReadRowsRetryListener.onClose(
ReadRowsRetryListener.java:141
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fscanner%2FReadRowsRetryListener.java&line=141&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$2.onClose(
ChannelPool.java:209
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fio%2FChannelPool.java&line=209&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(
ClientCallImpl.java:422
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=422&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl.access$100(
ClientCallImpl.java:74
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=74&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(
ClientCallImpl.java:508
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=508&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(
ClientCallImpl.java:425
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=425&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(
ClientCallImpl.java:540
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=540&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at com.google.bigtable.repackaged.io.grpc.internal.ContextRunnable.run(
ContextRunnable.java:52
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FContextRunnable.java&line=52&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.SerializingExecutor$TaskRunner.run(
SerializingExecutor.java:152
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FSerializingExecutor.java&line=152&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
... 1 more Caused by: java.lang.IllegalStateException: Cannot create new
threads after the request thread stops. at
com.google.appengine.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:449)
at
com.google.apphosting.vmruntime.VmRequestThreadFactory.newThread(VmRequestThreadFactory.java:87)
at
com.google.bigtable.repackaged.com.google.common.util.concurrent.ThreadFactoryBuilder$1.newThread(
ThreadFactoryBuilder.java:162
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fcom%2Fgoogle%2Fcommon%2Futil%2Fconcurrent%2FThreadFactoryBuilder.java&line=162&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at
java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
at
java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
at
java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368)
at com.google.bigtable.repackaged.io.grpc.internal.DnsNameResolver.resolve(
DnsNameResolver.java:205
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FDnsNameResolver.java&line=205&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>)
at com.google.bigtable.repackaged.io.grpc.internal.DnsNameResolver.start(
DnsNameResolver.java:116
<https://console.cloud.google.com/debug/fromlog?appModule=default&appVersion=20170210t163147&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FDnsNameResolver.java&line=116&logInsertId=589dd4770001238e8b086345&logNanos=1486738550211426000&nestedLogIndex=1&project=bigtable-dev>
)

**Comment by vc13819** [comment] 2017-02-11 13:41
So did some more digging around.
Our old code (the one w/o BigtableExtendedScan) continues to works with
0.9.4
but has the same problem as the SNAPSHOT with 0.9.5.1.
The problem is that when the Connection is getting initialized, under the
hoods, it appears some grpc threadpools are created which were
fine till 0.9.4. However 0.9.5.1 onwards they fail with the error

Caused by: java.lang.IllegalStateException: Request threads can only be
created within the context of a running request.
This error message is with the stack trace of createConnection
(Unfortunately the logs are printed in a way that stacktrace copy paste is
unwieldly).


We are using appengine flex setup. Since the error happens right at
initialization time, I think the gae-flex example that you have for cloud
bigtable examples will show this behaviour when you run it with 0.9.5.1.
(Our connection creation is "inspired" by the flex example!!)
https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/gae-flexible-helloworld

**Comment by sduskis** [comment] 2017-06-15 17:13
I'm going to close this.  The core of the original problem was solved.  The AppEngine related issues seem like a different problem, which should be tracked in a different issue.

**Closed by sduskis** 2017-06-15 17:13 UTC
