### ISSUE TITLE
Cannot use bigtable-hbase and bigtable-dataflow together

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-client#958] opened 2016-08-10 16:26 UTC
If the two jars are used together, the BigtableOpitons is one is shaded, but not in another. Cannot use them together.

**Comment by sduskis** [comment] 2016-08-10 16:46
This was fixed in one of the previous releases of the cloud bigtable client.  Which version are you on now?

**Comment by sduskis** [comment] 2016-08-10 18:33
I'm closing this issue, since I don't think this is an actionable request on our end.  Please upgrade to the latest client.  If that does not work, please reopen this issue.

**Comment by vc13819** [comment] 2016-08-11 02:05
I am using 0.9.1. This is the latest release. Reopening the issue.

**Comment by sduskis** [comment] 2016-08-11 02:47
Can you please help me reproduce this problem?  Code snippets and pom.xml are welcome.

**Comment by sduskis** [comment] 2016-08-11 03:25
FYI, if you want to use bigtable-hbase, see https://github.com/sduskis/cloud-bigtable-examples/tree/master/java/dataflow-connector-examples for the way we do it.  If you'd like, feel free to reach out to me in the email on my profile with more detailed information, or you can add the information here.

**Comment by sduskis** [comment] 2016-08-11 20:52
maybe this helps... There are two versions of BigtableOptions and BigtableSession.  Use the ones prefixed by the package name: com.google.bigtable.repackaged.com.google.cloud

**Comment by vc13819** [comment] 2016-08-12 03:53
The following code when compiled with both bigtable-hbase-1.1 and
bigtable-dataflow in

its dependencies. The version I am using is 0.9.1

Note that the usage of Options is done deep into a jar (not in the code I

have written). I do not even have an import for BigtableOptions in my code.

public static void main(String... args) {
  CloudBigtableOptions options =
      PipelineOptionsFactory.fromArgs(args).withValidation().as(CloudBigtableOptions.class);
  options.setBigtableInstanceId(System.getProperty("bigtable-instance-id"));
  options.setBigtableProjectId(System.getProperty("bigtable-project-id"));
  options.setBigtableTableId(System.getProperty("bigtable-name"));
  options.setStagingLocation("gs://" +
      System.getProperty("storage-bucket-id") + "/staging/dataflow");
  Scan scan = new Scan();
  scan.addFamily("p".getBytes());
  scan.setCacheBlocks(false);
  CloudBigtableScanConfiguration config =
CloudBigtableScanConfiguration.fromCBTOptions(options)
      .toBuilder().withScan(scan).build();
  Pipeline p = Pipeline.create(options);
  p
      .apply(Read.from(CloudBigtableIO.read(config)))
          "gs://" + System.getProperty("storage-bucket-id") + "/topic-dump"));
  p.run();
}

**Comment by sduskis** [comment] 2016-08-12 04:08
Gotcha.  We shade bigtable-hbase into bigtable-hbase-dataflow, i.e. the relevant components of bigtable-hbase are in bigtable-hbase-dataflow, but the packages are renamed.  If you remove bigtable-hbase-1.1, you should be good to go.  Sorry for the confusion.

**Comment by sduskis** [comment] 2016-08-12 16:13
I'll categorize this as a bug in our shading process.  It shouldn't be too hard to fix for the next release.  Thanks for the catch, and sorry for the trouble.  In the meantime, removing bigtable-hbase.* will fix the problem.

**Comment by sduskis** [comment] 2016-08-29 21:07
This was fixed with the 0.9.2 release.

**Closed by sduskis** 2016-08-29 21:07 UTC

**Comment by vc13819** [comment] 2016-09-10 10:08
Thanks Solomon.
I do not see bigtable-client 0.9.2 version in mvnrepository (there are
0.9.2 version for a bunch of related artifacts though bigtable-hbase,
bigtable-dataflow etc...).
https://mvnrepository.com/artifact/com.google.cloud.bigtable/bigtable-client

**Comment by sduskis** [comment] 2016-09-11 00:40
bigtable-client was a parent project that I didn't expect anyone to rely on.  I renamed bigtable-client to bigtable-client-parent.
